# Generated by Django 3.1.7 on 2021-03-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20210320_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user_id',
            new_name='owner',
        ),
    ]
