# Generated by Django 3.1.7 on 2021-03-21 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20210320_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created',
        ),
    ]
