# Generated by Django 3.1.7 on 2021-03-22 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_remove_product_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='owner',
            new_name='owner_id',
        ),
    ]
